// Mocks generated by Mockito 5.4.4 from annotations
// in quill_native_bridge_android/test/quill_native_bridge_android_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:typed_data' as _i3;

import 'package:mockito/mockito.dart' as _i1;

import 'test_api.g.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TestQuillNativeBridgeApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockTestQuillNativeBridgeApi extends _i1.Mock
    implements _i2.TestQuillNativeBridgeApi {
  MockTestQuillNativeBridgeApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void copyHtmlToClipboard(String? html) => super.noSuchMethod(
        Invocation.method(
          #copyHtmlToClipboard,
          [html],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void copyImageToClipboard(_i3.Uint8List? imageBytes) => super.noSuchMethod(
        Invocation.method(
          #copyImageToClipboard,
          [imageBytes],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void openGalleryApp() => super.noSuchMethod(
        Invocation.method(
          #openGalleryApp,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i4.Future<void> saveImageToGallery(
    _i3.Uint8List? imageBytes, {
    required String? name,
    required String? fileExtension,
    required String? mimeType,
    required String? albumName,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveImageToGallery,
          [imageBytes],
          {
            #name: name,
            #fileExtension: fileExtension,
            #mimeType: mimeType,
            #albumName: albumName,
          },
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
